### ISSUE TITLE
Collect more patron data?

### ISSUE THREAD

**Issue by deadlyraptor** [deadlyraptor/contact-copy#6]
Now that this script automates so much of the manual labor, it could stand to collect more than just the names and email addresses of the customers.

Potential data to collect includes:
- Home address
- Zipcode
- Phone number

**Comment by BenDelgado** [comment]
It may be easy yo collect more data, but to what end? The current data is to input into CC. Would the other info be used for membership drives (phone); income demographics determined by neighborhood (zip); direct mailing campaigns (home address)? If we ever plan on doing any of that, I can see a use for it. Otherwise, it's not really necessary.

**Comment by deadlyraptor** [comment]
Those are some of the use cases I had in mind, @BenDelgado. Don't some grants also want demographic data? At least, location-wise? Because there's no work for the user (the script is handling all of it) there doesn't seem to be any downside to collecting that information and making our database more robust.

**Comment by deadlyraptor** [comment]
Pull request #7 took care of this issue. The script now collects the patron's address, city, state, zip and phone number.
